# 快速教程

## 前期准备

在阅读这份教程之前，你应该懂一些关于 Python 的知识。如果你希望加深一下印象，你可以阅读 [这份教程](http://docs.python.org/tut/) 。

## 基础使用

NumPy 的基本对象是同类型、多维的数组。它是许多同类型的元素所构成的一张表。索引为一个包含正数的元组。在 NumPy 中，维数被称为轴。轴的个数被称为秩。

如，三维空间中一个点的坐标 <kbd>[1, 2, 3]</kbd>，为一个秩为 1 的数组，因为它只有一个轴，那个轴的长度为 3 。

NumPy 的数组类叫做 <kbd>ndarray</kbd> 。我们通常称它为 <kbd>array</kbd>。记住 NumPy 中的 <kbd>numpy.array</kbd> 与 Python 标准库中的 <kbd>array.array</kbd> 不同。它只可以处理一维数组且提供的功能也更少。以下为一些重要的 <kbd>ndarray</kbd> 对象的属性：

* **ndarray.ndim** 数组的轴数。在 Python 的世界中，轴数就是秩。 

* **ndarray.shape** 数组的尺寸。这是一个有数组的大小组成的整数元组。如：一个 n 行 m 列 的数组，它的 shape 为 <kbd>(n,m)</kbd>。这个元组的长度为数组的秩，上面的例子中预祝长度为 2 。

* **ndarray.size** 元素的个数，运行结果为 <kbd>ndarray.shape</kbd> 中元素的乘积。

* **ndarray.dtype** 一个描述数组中元素的类型的对象。dtype 可以为标准的 Python 类型，也可以为 NumPy 中特有的类型如：int32,float64

* **ndarray.itemsize** 数组中威哥元素的内存大小，单位为字节。如：一个元素为 float64 的数组大小为 <kbd>8(=64/8)</kbd> 。

* **ndarray.data** 一个包含一个数组所有元素的缓冲区。一般情况下，我们不去使用它，因为我们可以直接访问原数组。

### 一个例子

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

### 创建数组

我们可以通过多种方式创建一个数组。
如，我们可以通过一个 Python list 或 tuple 使用 <kbd>array</kbd> 函数来创建数组。

In [12]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b = np.array([1.2,3.5,5.1])
b

array([ 1.2,  3.5,  5.1])

In [15]:
b.dtype

dtype('float64')

这里有一个常见的错误，直接传入几个数字作为元素而不是传入一个序列。

In [16]:
a = np.array(1,2,3,4)  #错误

ValueError: only 2 non-keyword arguments accepted

In [17]:
a = np.array([1,2,3,4])  #正确

高维数组可以由嵌套列表或元组产生

In [18]:
b = np.array([(1.5,2,3),(4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

数组的数据类型可以在创建时指定

In [19]:
c = np.array([[1,2],[3,4]],dtype = complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

有些时候在创建数组时，数组元素未知，我们可以使用个NumPy 提供的一些防暑来创建具有占位数据的数组。

<kbd>zeros</kbd> 函数创建一个元素全为 0 的数组。 <kbd>ones</kbd> 函数创建一个元素均为 1 的数组。
<kbd>empty</kbd> 函数创建一个元素随机的数组，默认数据类型为 <kbd>float64</kbd> 。

In [20]:
np.zeros((3,4))  #传入一个元组

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
np.ones((2,3,4),dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

如要创建一列连续数字的数组，NumPy 提供了一个 <kbd>arange</kbd> 函数来创建这种数组。

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

### 显示数组

当你想要显示一个数组时，NumPy 以列表的形式显示。显示格式如下：

* 轴从上到下依次排列，第一个轴在最上方，最后一个在最下方。

* 轴中的元素从左到右排列。

一维数组以向量的形式显示，二维数组以矩阵形式显示，三维数组以矩阵列表的形式显示。

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


如果一个数组因太大而无法显示，NumPy 将自动跳过中间的元素，只显示开头和末尾的元素。

In [31]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [32]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


### 基础操作

对数组进行算数运算时，将对数组的每一个元素进行运算。将创建一个新数组来存放结果。

In [33]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [34]:
b ** 2

array([0, 1, 4, 9])

In [35]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a < 35

array([ True,  True, False, False], dtype=bool)

与其他矩阵式语言不同，在 NumPy中运算符 <kbd>*</kbd> 为每一个元素相乘，而不是矩阵乘法。矩阵乘法操作为 <kbd>dot</kbd> 函数。

In [37]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [38]:
A * B

array([[2, 0],
       [0, 4]])

In [39]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

像 <kbd>+=</kbd> 和 <kbd>-=</kbd> 运算符，它们原酸结果直接更改原数组，不创建新数组。

In [41]:
a = np.ones((2,3),dtype = int)
b = np.random.random((2,3))

In [42]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [43]:
b += a
b

array([[ 3.14133442,  3.06832192,  3.38531163],
       [ 3.27325825,  3.326512  ,  3.05378157]])